# -*- coding: utf-8 -*-
"""Traffic and People detection predict - Yolov8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1paL6EplhgY-GGqAwiwayJrVWFYWtv8ez
"""

!pip install ultralytics

from google.colab import drive
drive.mount('/content/drive/')

from ultralytics import YOLO
import cv2, os

model = YOLO('/content/drive/MyDrive/VisDrone/visdrone-yolov8.pt')

model.predict(
    source='nyc.mp4',
    save=True,
    conf=0.5
)