# -*- coding: utf-8 -*-
"""Traffic and People detection training - Yolov8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jL5JEJfX9_3whBKVyTBFf3uyjLG8FSD5
"""

!pip install ultralytics

from ultralytics import YOLO
import cv2, os

from google.colab import drive
drive.mount('/content/drive')

!unzip /content/drive/MyDrive/people-detection.zip -d /content/drive/MyDrive/people-detection/

!cp -r /content/drive/MyDrive/VisDrone/VisDrone_Dataset/ /content/

model = YOLO('yolov8n.pt')

model.train(
    data='VisDrone_Dataset/visdrone.yaml',
    epochs=100,
    imgsz=640,
    batch=16,
    name='visdrone-yolov8'
)

!cp runs/detect/visdrone-yolov8/weights/best.pt  /content/drive/MyDrive/VisDrone/visdrone-yolov8.pt

model.predict(
    source='test.mp4',
    conf=0.3,
    save=True
)